### PR TITLE
remove deprecated userstream and update to use tweepy for python 3.7

### PR DESCRIPTION
**Pull request by brandonmbanks**

### CODE REVIEW

**Comment by banks117** [comment]
Unfortunately userstream is no longer available by api. And would return status code 410.
tweepy/tweepy#1092

According to Twitter's API docs:
410 | Gone | This resource is gone. Used to indicate that an API endpoint has been turned off.

This PR removes the option from twweet-cli.

I also was running into problems running twweet-cli with python 3.7. Because async is a reserved word. This was fixed in tweepy but hasn't been released yet. Please let me know what your thoughts are on this.

tweepy/tweepy#1042

**Comment by banks117** [comment]
We could use `home_timeline` to almost mirror the functionality. It just won't be a stream.

**Comment by CruiseDevice** [comment]
If the userstream is no longer available, then i think `home_timeline` might be the good option.

**Comment by hugovk** [comment]
There is now a Tweepy release supporting Python 3.7.

https://pypi.org/project/tweepy/3.7.0/
https://github.com/tweepy/tweepy/releases/tag/3.7.0

**Pull request merged**
