### PR TITLE
increasing user interaction

### PR DESCRIPTION
**Pull request by Griffintaur**

### CODE REVIEW

**Comment by Griffintaur** [comment]
@CruiseDevice  can u check this.
This allows user to do multiple queries and feel more interactive

**Comment by 0x006E** [comment]
Please check this issue. #25 . Its more interactive than yours :+1:

**Comment by Griffintaur** [comment]
If you look into the code, there are options which allow user to go back to the main menu or continue with the different task in the same menu. and as far as taking input as a number to either move back or quit, I just did it to remain consistent with existing approach. If you want to switch to option based approach, it's simple one-word change there. Thus I find no way #25  handle it in a better way. If you see #25 calls for showing the main menu repeatedly until the user asks to quit. This doesn't handle every use case in a proper manner. That's my opinion @nithinswarrier

**Comment by 0x006E** [comment]
I just didn't say that yours is not worse than his. I just said I think words are better than numbers

**Comment by CruiseDevice** [comment]
@nithinswarrier @Griffintaur don't worry we can change it later. Its not a big deal.

**Comment by 0x006E** [comment]
True. Yeah Lets focus on the UI/UX

**Pull request merged**
