### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Shrey97**
Writing python3 explicitly made it clear that python3.x is required.

### CODE REVIEW

**Comment by dibyasonu** [comment]
No, for windows users who have installed python 3 we still write "python setup.py" so...

**Comment by utkarshkvs1** [comment]
I think we should keep seperate command for windows and linux then @Shrey97 .

**Comment by Shrey97** [comment]
Okay, that's fine.

**Comment by 0x006E** [comment]
This should be published to PyPi soon. So the command should make no difference then.

**Comment by CruiseDevice** [comment]
Yes once eveything is fixed, it has to be published on pypi. There must be one stable version for everyone to install. For temporary purpose we can put the old commit in the readme file which works.

**Comment by CruiseDevice** [comment]
As @utkarshkvs1  says, why not mention separate instructions for windows and linux?

**Pull request merged**
