### PR TITLE
Created setup.py

### PR DESCRIPTION
**Pull request by 0x006E**
I created a simple setup.py for this project

### CODE REVIEW

**Comment by CruiseDevice** [comment]
doing `python setup.py install` will install it on the local system? Have you tested it on your machine? Can you tweet after installing it on your local machine? If you were successful after installing, then please mention the steps, how did you run the application after installing. As no testing is involved in this project, i want to make sure that merging should not brake the project.

**Comment by 0x006E** [comment]
Ok. Thanks for the reply. I will test it on my machine

**Comment by 0x006E** [comment]
Hey. I have some doubts on the file twweet-cli.py. I cant get it to work. How can I add twitter API details without editing the file or after installing using the setup.py. To fix this I thin adding an option to add API details or if there is API details then an option to edit it.

**Comment by CruiseDevice** [comment]
I think we should ask the user while installing to enter there api details. And somehow record there response and store in `cfg` of twweet-cli.py. Yes adding an option to add API is a great idea. Maybe this can be done while installing or while running the twweet-cli.py file.

**Comment by CruiseDevice** [comment]
@nithinswarrier You can create a new issue for that.

**Comment by 0x006E** [comment]
The setup.py works correctly on my system only the twweet-cli.py. Cannot work correctly. I will look on that on a new issue

**Comment by CruiseDevice** [comment]
Hey! can you tell me what keyword you are using to run the application after installing? Are you still running the twweet-cli.py normally as we run?

**Comment by 0x006E** [comment]
I used python -m twweet-cli to run the app

**Comment by CruiseDevice** [comment]
@nithinswarrier Ok. this looks nice. I just tested it on my machine. It is working nicely. I'm merging this.

Thanks.

**Pull request merged**
