### PR TITLE
Added a stream listener

### PR DESCRIPTION
**Pull request by blavejr**
I added the stream listener so the user gets a constant stream of tweets.

### CODE REVIEW

**Comment by 0x006E** [comment]
Please update your fork with main repo.. And the DB use has been changed to JSON in the master branch.  Akash please check this and merge.

**Comment by 0x006E** [comment]
And also remove all hidden folder from the fork please. Its not needed by the program. Remember these when sending a PR

**Comment by CruiseDevice** [comment]
@blavejr Looks like this pr has lots of files that are unnecessary as @nithinswarrier said. Can you please remove those files and send the pr once again,

**Comment by blavejr** [comment]
Alright.

**Comment by blavejr** [comment]
Removed those files

**Comment by 0x006E** [comment]
Brw. Please update your fork. A lot has changed from the time you opened PR to this present. Please update this.

**Comment by blavejr** [comment]
Alright, I made the needed changes. There is a problem with closing the stream, I don't know how to end it without ending the entire program but I guess that's an issue we can fix later as we move on.

**Comment by 0x006E** [comment]
Ohk. Tag @CruiseDevice in a comment. He will check the code. Anyway gd one

**Comment by blavejr** [comment]
@CruiseDevice check this out.

**Comment by CruiseDevice** [comment]
@blavejr merged :+1:  Good work.

**Comment by 0x006E** [comment]
Brw. Is this code working? Or is this code based python 2.7??? I just have an doubt. When running with python3 its gives me syntax error. Please check this out. 
screenshot from 2017-08-23 18-43-20

**Comment by CruiseDevice** [comment]
@nithinswarrier just use `python twweet_cli.py`

**Comment by 0x006E** [comment]
Now the code is a mixture of 2.7 and 3 ryt? Or Am I wrong?

**Comment by CruiseDevice** [comment]
Yes i guess so. :smile:

**Comment by 0x006E** [comment]
Now option 4 is also not working in get.

**Comment by CruiseDevice** [comment]
it is working for me.

**Comment by CruiseDevice** [comment]
all the options are working right for me. Options that use stream are taking a little time, but they are working.

**Comment by 0x006E** [comment]
Yea its working.. its taking a lot of time..

**Comment by CruiseDevice** [comment]
@nithinswarrier maybe a new issue for performance improvement.

**Comment by blavejr** [comment]
I wrote it use python 2.7

**Comment by blavejr** [comment]
When streaming it takes a while for tweets to come up because its not getting old tweets only brand new ones, so they tweets show up as they come in. it depends on how active your Timeline is

**Comment by blavejr** [comment]
but I guess right now the only major difference is that my print statements do not have parenthesis. if you add those it should run for Python 3 as well. I think

**Comment by 0x006E** [comment]
But now the code has both python 3 and python 2.7. Please make it python 3. And when getting stream just add a text "Loading stream." instead of printing the main menu. It makes the user confused. Plz fix this :+1:

**Comment by blavejr** [comment]
oh, I'm not sure why it prints the menu again, I think it has something to do with the loop but I will look into it.

**Pull request merged**
